### ISSUE TITLE
Additional component-plans

### ISSUE THREAD

**Issue by rbossy** [openminted/alvis-docker#11]
There here: https://github.com/openminted/alvis-docker/tree/master/openminted-components/segmenter/test-data/plans

* [`OMTD_GeniaTagger.plan`](https://github.com/openminted/alvis-docker/blob/master/openminted-components/segmenter/test-data/plans/OMTD_GeniaTagger.plan): segmentation, POS-tagging, lemmatization, NER (*DNA*, *cell_line*, *cell_type*, *PROTEIN*).
* [`OMTD_RDFProjector.plan`](https://github.com/openminted/alvis-docker/blob/master/openminted-components/segmenter/test-data/plans/OMTD_RDFProjector.plan) and its resource [`Wheat-Trait-Ontology-1.2.xrdf`](https://github.com/openminted/alvis-docker/blob/master/openminted-components/segmenter/test-data/plans/Wheat-Trait-Ontology-1.2.xrdf): segmentation, POS-tagging, lemmatization, NER (*phenotype*). Wherever the resource is located, the path should be set right at [line 15](https://github.com/openminted/alvis-docker/blob/66a76f623b46690c08ac490a6144fd684b6b6f58/openminted-components/segmenter/test-data/plans/OMTD_RDFProjector.plan#L15).
* [`OMTD_ToMap.plan`](https://github.com/openminted/alvis-docker/blob/master/openminted-components/segmenter/test-data/plans/OMTD_ToMap.plan) and its resource [`OntoBiotope_BioNLP-ST-2016-Habitat.tomap`](https://github.com/openminted/alvis-docker/blob/master/openminted-components/segmenter/test-data/plans/OntoBiotope_BioNLP-ST-2016-Habitat.tomap): segmentation, POS-tagging, lemmatization, NER (*habitat*). Wherever the resource is located, the path should be set at [line 19](https://github.com/openminted/alvis-docker/blob/66a76f623b46690c08ac490a6144fd684b6b6f58/openminted-components/segmenter/test-data/plans/OMTD_ToMap.plan#L19).
* [`OMTD_RegExp.plan`](https://github.com/openminted/alvis-docker/blob/master/openminted-components/segmenter/test-data/plans/OMTD_RegExp.plan): juste regular expression matching. Accepts a parameter named `pattern` which is a regular expression in Java syntax.

@mandiayba

**Comment by mandiayba** [comment]
Have the following error, don't know why ? 
```
[2018-05-11 09:23:10.489][alvisnlp] finished loading /alvisnlp/OMTD_ToMap.plan
[2018-05-11 09:23:10.490][alvisnlp] setting input to '/alvisnlp/data/corpus' in OMTD_ToMap
[2018-05-11 09:23:10.495][alvisnlp] SEVERE unset mandatory parameter: tt parFile
[2018-05-11 09:23:10.496][alvisnlp] SEVERE error in plan: some mandatory parameters are not set
```

**Comment by rbossy** [comment]
Replaced `TreeTagger` with `GeniaTagger` in commit fe1fa48feff160906ef5d45dbf123dd3149d51ea

@mandiayba

**Comment by mandiayba** [comment]
the plans work fine
